# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'table.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_2(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1020, 690)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget {\n"
"    color: white;\n"
"    background-color: #121212;\n"
"    font-family: Rubik;\n"
"    font-size: 10pt;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: transparent;\n"
"    border: 1px solid #49423d;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #666;\n"
"}\n"
"\n"
"QPushButton:!hover {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #24b3a7;\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.Table = QtWidgets.QTextEdit(self.centralwidget)
        self.Table.setGeometry(QtCore.QRect(10, 20, 230, 390))
        self.Table.setReadOnly(True)
        self.Table.setTabStopWidth(80)
        self.Table.setObjectName("Table")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 415, 360, 20))
        self.label.setObjectName("label")
        self.PDNF = QtWidgets.QTextEdit(self.centralwidget)
        self.PDNF.setGeometry(QtCore.QRect(10, 450, 1000, 60))
        self.PDNF.setReadOnly(True)
        self.PDNF.setObjectName("PDNF")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 525, 360, 20))
        self.label_2.setObjectName("label_2")
        self.PCNF = QtWidgets.QTextEdit(self.centralwidget)
        self.PCNF.setGeometry(QtCore.QRect(10, 560, 1000, 60))
        self.PCNF.setReadOnly(True)
        self.PCNF.setObjectName("PCNF")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(270, 120, 200, 15))
        self.label_3.setObjectName("label_3")
        self.Zhegalkin = QtWidgets.QTextEdit(self.centralwidget)
        self.Zhegalkin.setGeometry(QtCore.QRect(270, 150, 740, 60))
        self.Zhegalkin.setReadOnly(True)
        self.Zhegalkin.setObjectName("Zhegalkin")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(270, 230, 491, 20))
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.Classes = QtWidgets.QTextEdit(self.centralwidget)
        self.Classes.setGeometry(QtCore.QRect(270, 260, 420, 32))
        self.Classes.setReadOnly(True)
        self.Classes.setObjectName("Classes")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(270, 20, 181, 20))
        self.label_5.setObjectName("label_5")
        self.OrigExp = QtWidgets.QTextEdit(self.centralwidget)
        self.OrigExp.setGeometry(QtCore.QRect(270, 50, 740, 32))
        self.OrigExp.setReadOnly(True)
        self.OrigExp.setObjectName("OrigExp")
        self.Next = QtWidgets.QPushButton(self.centralwidget)
        self.Next.setGeometry(QtCore.QRect(270, 370, 90, 30))
        self.Next.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Next.setObjectName("Next")
        self.Copy_PDNF = QtWidgets.QPushButton(self.centralwidget)
        self.Copy_PDNF.setGeometry(QtCore.QRect(890, 510, 120, 28))
        self.Copy_PDNF.setObjectName("Copy_PDNF")
        self.Copy_PCNF = QtWidgets.QPushButton(self.centralwidget)
        self.Copy_PCNF.setGeometry(QtCore.QRect(890, 620, 120, 28))
        self.Copy_PCNF.setObjectName("Copy_PCNF")
        self.Copy_Zhegalkin = QtWidgets.QPushButton(self.centralwidget)
        self.Copy_Zhegalkin.setGeometry(QtCore.QRect(890, 210, 120, 28))
        self.Copy_Zhegalkin.setObjectName("Copy_Zhegalkin")
        self.Copy_Func = QtWidgets.QPushButton(self.centralwidget)
        self.Copy_Func.setGeometry(QtCore.QRect(890, 80, 120, 28))
        self.Copy_Func.setObjectName("Copy_Func")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Table.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Rubik\'; font-size:10pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label.setText(_translate("MainWindow", "СДНФ:"))
        self.PDNF.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Rubik\'; font-size:10pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "СКНФ:"))
        self.label_3.setText(_translate("MainWindow", "Полином Жегалкина:"))
        self.label_4.setText(_translate("MainWindow", "Принадлежит следующим классам по теореме Поста:"))
        self.label_5.setText(_translate("MainWindow", "Введённая функция"))
        self.Next.setText(_translate("MainWindow", "Далее"))
        self.Copy_PDNF.setText(_translate("MainWindow", "Копировать"))
        self.Copy_PCNF.setText(_translate("MainWindow", "Копировать"))
        self.Copy_Zhegalkin.setText(_translate("MainWindow", "Копировать"))
        self.Copy_Func.setText(_translate("MainWindow", "Копировать"))
